exports.OrderStatusEnum = {
  ORDERED: 'ORDERED',
  CANCELED: 'CANCELED',
  DELIVERING: 'DELIVERING',
  COMPLETED: 'COMPLETED',
  PURCHASED: 'PURCHASED',
  WAITING_FOR_REFUND: 'WAITING_FOR_REFUND',
  REFUNDED: 'REFUNDED',
};
